version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "5000:80"  # Change to use a different port as 80 is already in use
    volumes:
      - ./html:/usr/share/nginx/html  # Ensure ./html directory exists
    networks:
      - app-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql  # Ensure the volume is named and properly mapped

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Define a named volume for persistent MySQL data
